import Footer from '@/components/Footer';
import Navbar from '@/components/Navbar';
import { SessionProviders } from '@/libs/SessionProvider';
import { getUser } from '@/libs/getUser';
import { Poppins } from 'next/font/google';
import { Toaster } from 'react-hot-toast';
import './globals.css';

const poppins = Poppins({ subsets: ['latin'],weight:['300','400','500', '700'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const session = await getUser()
  return (
    <html lang="en">
      <body className={` bg-gray-50 text-gray-900 ${poppins.className}`}>
        <SessionProviders>
        <div className='max-w-[1200px] mx-auto p-1'>
        <Toaster />
        <Navbar />
        {children}
        <Footer />
        </div>
        </SessionProviders>
        </body>
    </html>
  )
}
